## CONSTANTS

# COLORS
BLACK = "black"
GREY = "grey"
DARKGREY = "darkgrey"
LIGHTGREY = "lightgrey"
RED = "red"
BLEACHEDDENIM = "#B0C4DE"
OCEANDENIM = "#4B5C77"
MIDNIGHTDENIM = "#2A3F54"
CLASSICDENIM = "#1560BD"
CREAM = "#FFFFCC"

# SHAPES
CIRCLE = "circle"
TRIANGLE = "triangle"
SQUARE = "square"
ARROW = "arrow"


## HUMANOID

# HEAD
FACE_WID = 0.5
FACE_LEN = 1.1
CRANIUM_WID = 0.9
CRANIUM_LEN = 0.8

# TORSO
SHOULDERS_WID = 0.4
SHOULDERS_LEN = 1
CHEST_WID = 1
CHEST_LEN = 1
WAIST_WID = 1
WAIST_LEN = 1.6
PELVIS_WID = 1
PELVIS_LEN = 1

# LEGS
THIGH_WID = 0.8
THIGH_LEN = 5
THIGH_SIZE = 50
CALF_WID = 0.5
CALF_LEN = 4
CALF_SIZE = 40
FOOT_WID = 1
FOOT_LEN = 0.5
MAX_EXTENDED = 300
MAX_RETRACTED = 240

# ARMS
UPPERARM_WID = 0.6
UPPERARM_LEN = 4
UPPERARM_SIZE = 40
FOREARM_WID = 0.4
FOREARM_LEN = 3
FOREARM_SIZE = 30
HAND_WID = 0.5
HAND_LEN = 0.5

# START POSITIONS
FACE_POS_X = 6
FACE_POS_Y = 87
FACE_HEADING = 270
CRANIUM_POS_X = 2
CRANIUM_POS_Y = 92
CRANIUM_HEADING = 270
SHOULDERS_POS_X = -2
SHOULDERS_POS_Y = 76
SHOULDERS_HEADING = 90
CHEST_POS_X = 0
CHEST_POS_Y = 60
CHEST_HEADING = 0
WAIST_POS_X = 0
WAIST_POS_Y = 40
WAIST_HEADING = 270
PELVIS_POS_X = -1
PELVIS_POS_Y = 10
PELVIS_HEADING = 0
THIGH_POS_X = 0
THIGH_POS_Y = 0
THIGH_HEADING = 270
CALF_POS_X = -2
CALF_POS_Y = -THIGH_SIZE
CALF_HEADING = 270
FOOT_POS_X = 5
FOOT_POS_Y = -THIGH_SIZE - CALF_SIZE - 4
FOOT_HEADING = 270
UPPERARM_POS_X = -2
UPPERARM_POS_Y = 65
UPPERARM_HEADING = 270
FOREARM_POS_X = 0
FOREARM_POS_Y = FOREARM_SIZE - 4
FOREARM_HEADING = 270
HAND_POS_X = 2
HAND_POS_Y = -4
HAND_HEADING = 0


## INFO

# START POSITIONS
INFO_POS_X = 0
INFO_POS_Y = -380


## SURFACE

# DIMENSIONS
SURFACE_WID = 0.05
SURFACE_LEN = 40

# START POSITIONS
SURFACE_POS_X = 0
SURFACE_POS_Y = -100
SURFACE_HEADING = 0


## BACKGROUND

# DIMENSIONS
BACKGROUND_EMPTY_MID_WID = 25
BACKGROUND_EMPTY_MID_LEN = 40
BACKGROUND_EMPTY_LEFT_WID = 25
BACKGROUND_EMPTY_LEFT_LEN = 40
BACKGROUND_EMPTY_RIGHT_WID = 25
BACKGROUND_EMPTY_RIGHT_LEN = 40
BACKGROUND_LIGHT_WID = 25
BACKGROUND_LIGHT_LEN = 40
BACKGROUND_REGULAR_WID = 25
BACKGROUND_REGULAR_LEN = 40
BACKGROUND_HEAVY_WID = 25
BACKGROUND_HEAVY_LEN = 40
BACKGROUND_CONVEYOR_WID = 25
BACKGROUND_CONVEYOR_LEN = 40

#START POSITIONS
BACKGROUND_EMPTY_MID_POS_X = 0
BACKGROUND_EMPTY_MID_POS_Y = 150
BACKGROUND_EMPTY_MID_HEADING = 0
BACKGROUND_EMPTY_LEFT_POS_X = -3200
BACKGROUND_EMPTY_LEFT_POS_Y = 150
BACKGROUND_EMPTY_LEFT_HEADING = 0
BACKGROUND_EMPTY_RIGHT_POS_X = 1600
BACKGROUND_EMPTY_RIGHT_POS_Y = 150
BACKGROUND_EMPTY_RIGHT_HEADING = 0
BACKGROUND_LIGHT_POS_X = -1600
BACKGROUND_LIGHT_POS_Y = 150
BACKGROUND_LIGHT_HEADING = 0
BACKGROUND_REGULAR_POS_X = -800
BACKGROUND_REGULAR_POS_Y = 150
BACKGROUND_REGULAR_HEADING = 0
BACKGROUND_HEAVY_POS_X = -2400
BACKGROUND_HEAVY_POS_Y = 150
BACKGROUND_HEAVY_HEADING = 0
BACKGROUND_CONVEYOR_POS_X = 800
BACKGROUND_CONVEYOR_POS_Y = 150
BACKGROUND_CONVEYOR_HEADING = 0

# EXTREME POSITIONS
LEFTMOST_TERM = -1600
RIGHTMOST_TERM = 3200
