## CONSTANTS

# SCREEN
SCREEN_WID: int = 800
SCREEN_HGT: int = 800
SCREEN_TRA: int = 0

# NAMES
CONST_X: str = "x"
CONST_Y: str = "y"
CONST_LIGHT: str = "light"
CONST_REGULAR: str = "regular"
CONST_HEAVY: str = "heavy"

# SPEEDS
SPEED: int = 0

# COLORS
BLACK: str = "black"
GREY: str = "grey"
DARKGREY: str = "darkgrey"
LIGHTGREY: str = "lightgrey"
RED: str = "red"
MAHOGANY: str = "#420D09"
MOCHA: str = "#654321"
COPPER: str = "#B87333"
FORESTGREEN: str = "#014421"
TROPICALRAINFOREST: str = "#00755E"
MIDNIGHTDENIM: str = "#2A3F54"
OCEANDENIM: str = "#4B5C77"
BLEACHEDDENIM: str = "#B0C4DE"
DAYSKYBLUE: str = "#82CAFF"
BOX_LIGHT_COLOR: str = COPPER
BOX_REGULAR_COLOR: str = MOCHA
BOX_HEAVY_COLOR: str = MAHOGANY

# SHAPES
ARROW: str = "arrow"
CIRCLE: str = "circle"
SQUARE: str = "square"
TRIANGLE: str = "triangle"

# FONTS
FONT_NAME: str = "Arial"
FONT_SIZE: int = 16
FONT_TYPE: str = "normal"

# MESSAGES
EXIT_MESSAGE: str = "Thanks for playing!"


## HUMANOID

# NAMES
NAME_FACE: str = "face"
NAME_CRANIUM: str = "cranium"
NAME_SHOULDERS: str = "shoulders"
NAME_CHEST: str = "chest"
NAME_WAIST: str = "waist"
NAME_PELVIS: str = "pelvis"
NAME_LEFT_THIGH: str = "left_thigh"
NAME_LEFT_CALF: str = "left_calf"
NAME_LEFT_FOOT: str = "left_foot"
NAME_RIGHT_THIGH: str = "right_thigh"
NAME_RIGHT_CALF: str = "right_calf"
NAME_RIGHT_FOOT: str = "right_foot"
NAME_LEFT_UPPERARM: str = "left_upperarm"
NAME_LEFT_FOREARM: str = "left_forearm"
NAME_LEFT_HAND: str = "left_hand"
NAME_RIGHT_UPPERARM: str = "right_upperarm"
NAME_RIGHT_FOREARM: str = "right_forearm"
NAME_RIGHT_HAND: str = "right_hand"

# SPEEDS
DEFAULT: float = 0.0001
SLOW: float = 0.005
NORMAL: float = 0.001
FAST: int = 0
ZERO: int = 0

# DIMENSIONS
FACE_WID: float = 0.5
FACE_LEN: float = 1.1
CRANIUM_WID: float = 0.9
CRANIUM_LEN: float = 0.8
SHOULDERS_WID: float = 0.4
SHOULDERS_LEN: int = 1
CHEST_WID: int = 1
CHEST_LEN: int = 1
WAIST_WID: int = 1
WAIST_LEN: float = 1.6
PELVIS_WID: int = 1
PELVIS_LEN: int = 1
THIGH_WID: float = 0.8
THIGH_LEN: int = 5
THIGH_SIZE: int = 50
CALF_WID: float = 0.5
CALF_LEN: int = 4
CALF_SIZE: int = 40
FOOT_WID: int = 1
FOOT_LEN: float = 0.5
MAX_EXTENDED: int = 300
MAX_RETRACTED: int = 240
UPPERARM_WID: float = 0.6
UPPERARM_LEN: int = 4
UPPERARM_SIZE: int = 40
FOREARM_WID: float = 0.4
FOREARM_LEN: int = 3
FOREARM_SIZE: int = 30
HAND_WID: float = 0.5
HAND_LEN: float = 0.5

# START POSITIONS
FACE_HEADING: int = 270
FACE_POS_X: int = 6
FACE_POS_Y: int = 87
CRANIUM_HEADING: int = 270
CRANIUM_POS_X: int = 2
CRANIUM_POS_Y: int = 92
SHOULDERS_HEADING: int = 90
SHOULDERS_POS_X: int = -2
SHOULDERS_POS_Y: int = 76
CHEST_HEADING: int = 0
CHEST_POS_X: int = 0
CHEST_POS_Y: int = 60
WAIST_HEADING: int = 270
WAIST_POS_X: int = 0
WAIST_POS_Y: int = 40
PELVIS_HEADING: int = 0
PELVIS_POS_X: int = -1
PELVIS_POS_Y: int = 10
THIGH_HEADING: int = 270
THIGH_POS_X: int = 0
THIGH_POS_Y: int = 0
CALF_HEADING: int = 270
CALF_POS_X: int = -2
CALF_POS_Y: int = -THIGH_SIZE
FOOT_HEADING: int = 270
FOOT_POS_X: int = 5
FOOT_POS_Y: int = -THIGH_SIZE - CALF_SIZE - 4
UPPERARM_HEADING: int = 270
UPPERARM_POS_X: int = -2
UPPERARM_POS_Y: int = 65
FOREARM_HEADING: int = 270
FOREARM_POS_X: int = 0
FOREARM_POS_Y: int = FOREARM_SIZE - 4
HAND_HEADING: int = 0
HAND_POS_X: int = 2
HAND_POS_Y: int = -4

# CARRY HEADING
CARRY_UPPERARM_HEADING: int = 270
CARRY_LEFT_FOREARM_HEADING: int = 180
CARRY_LEFT_FOREARM_POS_X: int = 0
CARRY_LEFT_FOREARM_POS_Y: int = -40
CARRY_LEFT_HAND_POS_X: int = 30
CARRY_LEFT_HAND_POS_Y: int = -38
CARRY_RIGHT_FOREARM_HEADING: int = 0
CARRY_RIGHT_FOREARM_POS_X: int = 0
CARRY_RIGHT_FOREARM_POS_Y: int = -40
CARRY_RIGHT_HAND_POS_X: int = 30
CARRY_RIGHT_HAND_POS_Y: int = -38


## BACKGROUND

# NAMES
BACKGROUND_EMPTY_MID_NAME: str = "background_empty_mid"
BACKGROUND_EMPTY_LEFT_NAME: str = "background_empty_left"
BACKGROUND_EMPTY_RIGHT_NAME: str = "background_empty_right"
BACKGROUND_LIGHT_NAME: str = "background_light"
LIGHT_LIFT_NAME: str = "light_lift"
BACKGROUND_REGULAR_NAME: str = "background_regular"
REGULAR_LIFT_NAME: str = "regular_lift"
BACKGROUND_HEAVY_NAME: str = "background_heavy"
HEAVY_LIFT_NAME: str = "heavy_lift"
BACKGROUND_CONVEYOR_NAME: str = "background_conveyor"
CONVEYOR_LIFT_NAME: str = "conveyor_lift"
CONVEYOR_BELT_NAME: str = "conveyor_belt"
CONVEYOR_DRIVE_NAME: str = "conveyor_drive"
CONVEYOR_TAIL_NAME: str = "conveyor_tail"

# SPEEDS
LIGHT_LIFT_SPEED: int = 1
REGULAR_LIFT_SPEED: int = 1
HEAVY_LIFT_SPEED: int = 1
CONVEYOR_LIFT_SPEED: int = 1

# DIMENSIONS
BACKGROUND_EMPTY_MID_WID: int = 19
BACKGROUND_EMPTY_MID_LEN: int = 40
BACKGROUND_EMPTY_LEFT_WID: int = 19
BACKGROUND_EMPTY_LEFT_LEN: int = 40
BACKGROUND_EMPTY_RIGHT_WID: int = 19
BACKGROUND_EMPTY_RIGHT_LEN: int = 40
BACKGROUND_LIGHT_WID: int = 25
BACKGROUND_LIGHT_LEN: int = 40
BACKGROUND_REGULAR_WID: int = 25
BACKGROUND_REGULAR_LEN: int = 40
BACKGROUND_HEAVY_WID: int = 25
BACKGROUND_HEAVY_LEN: int = 40
BACKGROUND_CONVEYOR_WID: int = 25
BACKGROUND_CONVEYOR_LEN: int = 40
LIGHT_LIFT_WID: float = 0.2
LIGHT_LIFT_LEN: int = 8
REGULAR_LIFT_WID: float = 0.2
REGULAR_LIFT_LEN: int = 8
HEAVY_LIFT_WID: float = 0.2
HEAVY_LIFT_LEN: int = 8
CONVEYOR_LIFT_WID: float = 0.2
CONVEYOR_LIFT_LEN: int = 8
CONVEYOR_BELT_WID: int = 2
CONVEYOR_BELT_LEN: int = 20
CONVEYOR_DRIVE_WID: int = 2
CONVEYOR_DRIVE_LEN: int = 2
CONVEYOR_TAIL_WID: int = 2
CONVEYOR_TAIL_LEN: int = 2

# START POSITIONS
BACKGROUND_EMPTY_MID_HEADING: int = 0
BACKGROUND_EMPTY_MID_POS_X: int = 0
BACKGROUND_EMPTY_MID_POS_Y: int = 210
BACKGROUND_EMPTY_LEFT_HEADING: int = 0
BACKGROUND_EMPTY_LEFT_POS_X: int = -3200
BACKGROUND_EMPTY_LEFT_POS_Y: int = 210
BACKGROUND_EMPTY_RIGHT_HEADING: int = 0
BACKGROUND_EMPTY_RIGHT_POS_X: int = 1600
BACKGROUND_EMPTY_RIGHT_POS_Y: int = 210
BACKGROUND_LIGHT_HEADING: int = 0
BACKGROUND_LIGHT_POS_X: int = -1600
BACKGROUND_LIGHT_POS_Y: int = 150
BACKGROUND_REGULAR_HEADING: int = 0
BACKGROUND_REGULAR_POS_X: int = -800
BACKGROUND_REGULAR_POS_Y: int = 150
BACKGROUND_HEAVY_HEADING: int = 0
BACKGROUND_HEAVY_POS_X: int = -2400
BACKGROUND_HEAVY_POS_Y: int = 150
BACKGROUND_CONVEYOR_HEADING: int = 0
BACKGROUND_CONVEYOR_POS_X: int = 800
BACKGROUND_CONVEYOR_POS_Y: int = 150
LIGHT_LIFT_HEADING: int = 0
LIGHT_LIFT_POS_X: int = 0
LIGHT_LIFT_POS_Y: int = 18
LIGHT_LIFT_MIN_Y: int = 18
LIGHT_LIFT_MAX_Y: int = 402
REGULAR_LIFT_HEADING: int = 0
REGULAR_LIFT_POS_X: int = 0
REGULAR_LIFT_POS_Y: int = 18
REGULAR_LIFT_MIN_Y: int = 18
REGULAR_LIFT_MAX_Y: int = 402
HEAVY_LIFT_HEADING: int = 0
HEAVY_LIFT_POS_X: int = 0
HEAVY_LIFT_POS_Y: int = 18
HEAVY_LIFT_MIN_Y: int = 18
HEAVY_LIFT_MAX_Y: int = 402
CONVEYOR_LIFT_HEADING: int = 0
CONVEYOR_LIFT_POS_X: int = 305
CONVEYOR_LIFT_POS_Y: int = -98
CONVEYOR_LIFT_MIN_Y: int = -98
CONVEYOR_LIFT_MAX_Y: int = 18
CONVEYOR_BELT_HEADING: int = 0
CONVEYOR_BELT_POS_X: int = 0
CONVEYOR_BELT_POS_Y: int = 0
CONVEYOR_DRIVE_HEADING: int = 0
CONVEYOR_DRIVE_POS_X: int = -200
CONVEYOR_DRIVE_POS_Y: int = 0
CONVEYOR_TAIL_HEADING: int = 0
CONVEYOR_TAIL_POS_X: int = 200
CONVEYOR_TAIL_POS_Y: int = 0

# EXTREME POSITIONS
LEFTMOST_TERM: int = -1600
RIGHTMOST_TERM: int = 3200

# ENTER FACTORY
FACTORY_LEFT_END: int = 400
FACTORY_RIGHT_END: int = -400


## BOX

# NAMES
NAME_LIGHT_BOX: str = "light_box"
NAME_REGULAR_BOX: str = "regular_box"
NAME_HEAVY_BOX: str = "heavy_box"

# SPEEDS
BOX_LEFT_SPEED: int = -1

# DIMENSIONS
BOX_LIGHT_SHAPESIZE: tuple = (1, 1, 1)
BOX_LIGHT_WID: int = 1
BOX_LIGHT_LEN: int = 1
BOX_REGULAR_SHAPESIZE: tuple = (2, 2, 1)
BOX_REGULAR_WID: int = 2
BOX_REGULAR_LEN: int = 2
BOX_HEAVY_SHAPESIZE: tuple = (3, 3, 1)
BOX_HEAVY_WID: int = 3
BOX_HEAVY_LEN: int = 3

# CARRY POSITIONS
LIGHT_BOX_HEADING: int = 0
LIGHT_BOX_POS_X: int = 30
LIGHT_BOX_POS_Y: int = 43
REGULAR_BOX_HEADING: int = 0
REGULAR_BOX_POS_X: int = 35
REGULAR_BOX_POS_Y: int = 53
HEAVY_BOX_HEADING: int = 0
HEAVY_BOX_POS_X: int = 45
HEAVY_BOX_POS_Y: int = 63

# TRANSPORT POSITIONS
TRANSPORT_X: int = 0
LIGHT_TRANSPORT_Y: int = 13
REGULAR_TRANSPORT_Y: int = 23
HEAVY_TRANSPORT_Y: int = 33

# PICK UP POSITIONS
BOX_PICKUP_POS_X: int = -1000

# ABOVE SCREEN POSITIONS
BOX_ABOVE_SCREEN_POS_X: int = 0
BOX_ABOVE_SCREEN_POS_Y: int = 500

# HELPERS
ADJUST_Y: int = 0
BOX_INDEX: int = -1


## SURFACE

# DIMENSIONS
SURFACE_WID: float = 0.05
SURFACE_LEN: int = 40

# START POSITIONS
SURFACE_HEADING: int = 0
SURFACE_POS_X: int = 0
SURFACE_POS_Y: int = -100


## INFO

# START POSITIONS
INFO_POS_X: int = 0
INFO_POS_Y: int = -380
INFO_ALIGN: str = "center"

# TEXT
INFO_TEXT: str = "Use Left and Right arrow keys to control humanoid"
