## CONSTANTS

# NAMES
CONST_X = "x"
CONST_Y = "y"
CONST_LIGHT = "light"
CONST_REGULAR = "regular"
CONST_HEAVY = "heavy"

# SCREEN
SCREEN_WID = 800
SCREEN_HGT = 800
SCREEN_TRA = 0

# COLORS
BLACK = "black"
GREY = "grey"
DARKGREY = "darkgrey"
LIGHTGREY = "lightgrey"
RED = "red"
MAHOGANY = "#420D09"
MOCHA = "#654321"
COPPER = "#B87333"
FORESTGREEN = "#014421"
TROPICALRAINFOREST = "#00755E"
MIDNIGHTDENIM = "#2A3F54"
OCEANDENIM = "#4B5C77"
BLEACHEDDENIM = "#B0C4DE"
DAYSKYBLUE = "#82CAFF"
BOX_LIGHT_COLOR = COPPER
BOX_REGULAR_COLOR = MOCHA
BOX_HEAVY_COLOR = MAHOGANY

# SHAPES
ARROW = "arrow"
CIRCLE = "circle"
SQUARE = "square"
TRIANGLE = "triangle"

# FONTS
FONT_NAME = "Arial"
FONT_SIZE = 16
FONT_TYPE = "normal"

# SPEEDS
SPEED = 0

# MESSAGES
EXIT_MESSAGE = "Thanks for playing!"


## HUMANOID

# NAMES
NAME_FACE = "face"
NAME_CRANIUM = "cranium"
NAME_SHOULDERS = "shoulders"
NAME_CHEST = "chest"
NAME_WAIST = "waist"
NAME_PELVIS = "pelvis"
NAME_LEFT_THIGH = "left_thigh"
NAME_LEFT_CALF = "left_calf"
NAME_LEFT_FOOT = "left_foot"
NAME_RIGHT_THIGH = "right_thigh"
NAME_RIGHT_CALF = "right_calf"
NAME_RIGHT_FOOT = "right_foot"
NAME_LEFT_UPPERARM = "left_upperarm"
NAME_LEFT_FOREARM = "left_forearm"
NAME_LEFT_HAND = "left_hand"
NAME_RIGHT_UPPERARM = "right_upperarm"
NAME_RIGHT_FOREARM = "right_forearm"
NAME_RIGHT_HAND = "right_hand"

# SPEEDS
DEFAULT = 0.0001
SLOW = 0.005
NORMAL = 0.001
FAST = 0
ZERO = 0

# DIMENSIONS
FACE_WID = 0.5
FACE_LEN = 1.1
CRANIUM_WID = 0.9
CRANIUM_LEN = 0.8
SHOULDERS_WID = 0.4
SHOULDERS_LEN = 1
CHEST_WID = 1
CHEST_LEN = 1
WAIST_WID = 1
WAIST_LEN = 1.6
PELVIS_WID = 1
PELVIS_LEN = 1
THIGH_WID = 0.8
THIGH_LEN = 5
THIGH_SIZE = 50
CALF_WID = 0.5
CALF_LEN = 4
CALF_SIZE = 40
FOOT_WID = 1
FOOT_LEN = 0.5
MAX_EXTENDED = 300
MAX_RETRACTED = 240
UPPERARM_WID = 0.6
UPPERARM_LEN = 4
UPPERARM_SIZE = 40
FOREARM_WID = 0.4
FOREARM_LEN = 3
FOREARM_SIZE = 30
HAND_WID = 0.5
HAND_LEN = 0.5

# START POSITIONS
FACE_HEADING = 270
FACE_POS_X = 6
FACE_POS_Y = 87
CRANIUM_HEADING = 270
CRANIUM_POS_X = 2
CRANIUM_POS_Y = 92
SHOULDERS_HEADING = 90
SHOULDERS_POS_X = -2
SHOULDERS_POS_Y = 76
CHEST_HEADING = 0
CHEST_POS_X = 0
CHEST_POS_Y = 60
WAIST_HEADING = 270
WAIST_POS_X = 0
WAIST_POS_Y = 40
PELVIS_HEADING = 0
PELVIS_POS_X = -1
PELVIS_POS_Y = 10
THIGH_HEADING = 270
THIGH_POS_X = 0
THIGH_POS_Y = 0
CALF_HEADING = 270
CALF_POS_X = -2
CALF_POS_Y = -THIGH_SIZE
FOOT_HEADING = 270
FOOT_POS_X = 5
FOOT_POS_Y = -THIGH_SIZE - CALF_SIZE - 4
UPPERARM_HEADING = 270
UPPERARM_POS_X = -2
UPPERARM_POS_Y = 65
FOREARM_HEADING = 270
FOREARM_POS_X = 0
FOREARM_POS_Y = FOREARM_SIZE - 4
HAND_HEADING = 0
HAND_POS_X = 2
HAND_POS_Y = -4

# CARRY HEADING
CARRY_UPPERARM_HEADING = 270
CARRY_LEFT_FOREARM_HEADING = 180
CARRY_LEFT_FOREARM_POS_X = 0
CARRY_LEFT_FOREARM_POS_Y = -40
CARRY_LEFT_HAND_POS_X = 30
CARRY_LEFT_HAND_POS_Y = -38
CARRY_RIGHT_FOREARM_HEADING = 0
CARRY_RIGHT_FOREARM_POS_X = 0
CARRY_RIGHT_FOREARM_POS_Y = -40
CARRY_RIGHT_HAND_POS_X = 30
CARRY_RIGHT_HAND_POS_Y = -38


## BACKGROUND

# NAMES
BACKGROUND_EMPTY_MID_NAME = "background_empty_mid"
BACKGROUND_EMPTY_LEFT_NAME = "background_empty_left"
BACKGROUND_EMPTY_RIGHT_NAME = "background_empty_right"
BACKGROUND_LIGHT_NAME = "background_light"
LIGHT_LIFT_NAME = "light_lift"
BACKGROUND_REGULAR_NAME = "background_regular"
REGULAR_LIFT_NAME = "regular_lift"
BACKGROUND_HEAVY_NAME = "background_heavy"
HEAVY_LIFT_NAME = "heavy_lift"
BACKGROUND_CONVEYOR_NAME = "background_conveyor"
CONVEYOR_LIFT_NAME = "conveyor_lift"
CONVEYOR_BELT_NAME = "conveyor_belt"
CONVEYOR_DRIVE_NAME = "conveyor_drive"
CONVEYOR_TAIL_NAME = "conveyor_tail"
TRACKPOINT_NAME = "trackpoint"

# SPEEDS
LIGHT_LIFT_SPEED = 1
REGULAR_LIFT_SPEED = 1
HEAVY_LIFT_SPEED = 1
CONVEYOR_LIFT_SPEED = 1

# DIMENSIONS
BACKGROUND_EMPTY_MID_WID = 19
BACKGROUND_EMPTY_MID_LEN = 40
BACKGROUND_EMPTY_LEFT_WID = 19
BACKGROUND_EMPTY_LEFT_LEN = 40
BACKGROUND_EMPTY_RIGHT_WID = 19
BACKGROUND_EMPTY_RIGHT_LEN = 40
BACKGROUND_LIGHT_WID = 25
BACKGROUND_LIGHT_LEN = 40
BACKGROUND_REGULAR_WID = 25
BACKGROUND_REGULAR_LEN = 40
BACKGROUND_HEAVY_WID = 25
BACKGROUND_HEAVY_LEN = 40
BACKGROUND_CONVEYOR_WID = 25
BACKGROUND_CONVEYOR_LEN = 40
LIGHT_LIFT_WID = 0.2
LIGHT_LIFT_LEN = 8
REGULAR_LIFT_WID = 0.2
REGULAR_LIFT_LEN = 8
HEAVY_LIFT_WID = 0.2
HEAVY_LIFT_LEN = 8
CONVEYOR_LIFT_WID = 0.2
CONVEYOR_LIFT_LEN = 8
CONVEYOR_BELT_WID = 2
CONVEYOR_BELT_LEN = 20
CONVEYOR_DRIVE_WID = 2
CONVEYOR_DRIVE_LEN = 2
CONVEYOR_TAIL_WID = 2
CONVEYOR_TAIL_LEN = 2

# START POSITIONS
BACKGROUND_EMPTY_MID_HEADING = 0
BACKGROUND_EMPTY_MID_POS_X = 0
BACKGROUND_EMPTY_MID_POS_Y = 210
BACKGROUND_EMPTY_LEFT_HEADING = 0
BACKGROUND_EMPTY_LEFT_POS_X = -3200
BACKGROUND_EMPTY_LEFT_POS_Y = 210
BACKGROUND_EMPTY_RIGHT_HEADING = 0
BACKGROUND_EMPTY_RIGHT_POS_X = 1600
BACKGROUND_EMPTY_RIGHT_POS_Y = 210
BACKGROUND_LIGHT_HEADING = 0
BACKGROUND_LIGHT_POS_X = -1600
BACKGROUND_LIGHT_POS_Y = 150
BACKGROUND_REGULAR_HEADING = 0
BACKGROUND_REGULAR_POS_X = -800
BACKGROUND_REGULAR_POS_Y = 150
BACKGROUND_HEAVY_HEADING = 0
BACKGROUND_HEAVY_POS_X = -2400
BACKGROUND_HEAVY_POS_Y = 150
BACKGROUND_CONVEYOR_HEADING = 0
BACKGROUND_CONVEYOR_POS_X = 800
BACKGROUND_CONVEYOR_POS_Y = 150
LIGHT_LIFT_HEADING = 0
LIGHT_LIFT_POS_X = 0
LIGHT_LIFT_POS_Y = 18
LIGHT_LIFT_MIN_Y = 18
LIGHT_LIFT_MAX_Y = 402
REGULAR_LIFT_HEADING = 0
REGULAR_LIFT_POS_X = 0
REGULAR_LIFT_POS_Y = 18
REGULAR_LIFT_MIN_Y = 18
REGULAR_LIFT_MAX_Y = 402
HEAVY_LIFT_HEADING = 0
HEAVY_LIFT_POS_X = 0
HEAVY_LIFT_POS_Y = 18
HEAVY_LIFT_MIN_Y = 18
HEAVY_LIFT_MAX_Y = 402
CONVEYOR_LIFT_HEADING = 0
CONVEYOR_LIFT_POS_X = 305
CONVEYOR_LIFT_POS_Y = -98
CONVEYOR_LIFT_MIN_Y = -98
CONVEYOR_LIFT_MAX_Y = 18
CONVEYOR_BELT_HEADING = 0
CONVEYOR_BELT_POS_X = 0
CONVEYOR_BELT_POS_Y = 0
CONVEYOR_DRIVE_HEADING = 0
CONVEYOR_DRIVE_POS_X = -200
CONVEYOR_DRIVE_POS_Y = 0
CONVEYOR_TAIL_HEADING = 0
CONVEYOR_TAIL_POS_X = 200
CONVEYOR_TAIL_POS_Y = 0

# EXTREME POSITIONS
LEFTMOST_TERM = -1600
RIGHTMOST_TERM = 3200

# ENTER FACTORY
FACTORY_LEFT_END = 400
FACTORY_RIGHT_END = -400


## BOX

# NAMES
NAME_LIGHT_BOX = "light_box"
NAME_REGULAR_BOX = "regular_box"
NAME_HEAVY_BOX = "heavy_box"

# SPEEDS
BOX_LEFT_SPEED = -1

# DIMENSIONS
BOX_LIGHT_SHAPESIZE = (1, 1, 1)
BOX_LIGHT_WID = 1
BOX_LIGHT_LEN = 1
BOX_REGULAR_SHAPESIZE = (2, 2, 1)
BOX_REGULAR_WID = 2
BOX_REGULAR_LEN = 2
BOX_HEAVY_SHAPESIZE = (3, 3, 1)
BOX_HEAVY_WID = 3
BOX_HEAVY_LEN = 3

# CARRY POSITIONS
LIGHT_BOX_HEADING = 0
LIGHT_BOX_POS_X = 30
LIGHT_BOX_POS_Y = 43
REGULAR_BOX_HEADING = 0
REGULAR_BOX_POS_X = 35
REGULAR_BOX_POS_Y = 53
HEAVY_BOX_HEADING = 0
HEAVY_BOX_POS_X = 45
HEAVY_BOX_POS_Y = 63

# TRANSPORT POSITIONS
TRANSPORT_X = 0
LIGHT_TRANSPORT_Y = 13
REGULAR_TRANSPORT_Y = 23
HEAVY_TRANSPORT_Y = 33

# PICK UP POSITIONS
BOX_PICKUP_POS_X = -1000

# ABOVE SCREEN POSITIONS
BOX_ABOVE_SCREEN_POS_X = 0
BOX_ABOVE_SCREEN_POS_Y = 500

# HELPERS
ADJUST_Y = 0
BOX_INDEX = -1


## TRACKPOINT

# DIMENSIONS
TRACKPOINT_WID = 0.2
TRACKPOINT_LEN = 0.2

# START POSITIONS
TRACKPOINT_HEADING = 0
TRACKPOINT_POS_X = BACKGROUND_CONVEYOR_POS_X + CONVEYOR_LIFT_POS_X
TRACKPOINT_POS_Y = CONVEYOR_LIFT_POS_Y
TRACKPOINT_MIN_Y = CONVEYOR_LIFT_MIN_Y
TRACKPOINT_MAX_Y = CONVEYOR_LIFT_MAX_Y


## SURFACE

# DIMENSIONS
SURFACE_WID = 0.05
SURFACE_LEN = 40

# START POSITIONS
SURFACE_HEADING = 0
SURFACE_POS_X = 0
SURFACE_POS_Y = -100


## INFO

# START POSITIONS
INFO_POS_X = 0
INFO_POS_Y = -380
INFO_ALIGN = "center"

# TEXT
INFO_TEXT = "Use Left and Right arrow keys to control humanoid"
