## CONSTANTS

# COLORS
BLACK = "black"
GREY = "grey"
DARKGREY = "darkgrey"
LIGHTGREY = "lightgrey"
RED = "red"
MAHOGANY = "#420D09"
MOCHA = "#654321"
COPPER = "#B87333"
TROPICALRAINFOREST = "#00755E"
DARKPASTELGREEN = "#03C03C"
MIDNIGHTDENIM = "#2A3F54"
OCEANDENIM = "#4B5C77"
BLEACHEDDENIM = "#B0C4DE"
DAYSKYBLUE = "#82CAFF"

# SHAPES
ARROW = "arrow"
CIRCLE = "circle"
SQUARE = "square"
TRIANGLE = "triangle"


## HUMANOID

# HEAD
FACE_WID = 0.5
FACE_LEN = 1.1
CRANIUM_WID = 0.9
CRANIUM_LEN = 0.8

# TORSO
SHOULDERS_WID = 0.4
SHOULDERS_LEN = 1
CHEST_WID = 1
CHEST_LEN = 1
WAIST_WID = 1
WAIST_LEN = 1.6
PELVIS_WID = 1
PELVIS_LEN = 1

# LEGS
THIGH_WID = 0.8
THIGH_LEN = 5
THIGH_SIZE = 50
CALF_WID = 0.5
CALF_LEN = 4
CALF_SIZE = 40
FOOT_WID = 1
FOOT_LEN = 0.5
MAX_EXTENDED = 300
MAX_RETRACTED = 240

# ARMS
UPPERARM_WID = 0.6
UPPERARM_LEN = 4
UPPERARM_SIZE = 40
FOREARM_WID = 0.4
FOREARM_LEN = 3
FOREARM_SIZE = 30
HAND_WID = 0.5
HAND_LEN = 0.5

# START POSITIONS
FACE_HEADING = 270
FACE_POS_X = 6
FACE_POS_Y = 87
CRANIUM_HEADING = 270
CRANIUM_POS_X = 2
CRANIUM_POS_Y = 92
SHOULDERS_HEADING = 90
SHOULDERS_POS_X = -2
SHOULDERS_POS_Y = 76
CHEST_HEADING = 0
CHEST_POS_X = 0
CHEST_POS_Y = 60
WAIST_HEADING = 270
WAIST_POS_X = 0
WAIST_POS_Y = 40
PELVIS_HEADING = 0
PELVIS_POS_X = -1
PELVIS_POS_Y = 10
THIGH_HEADING = 270
THIGH_POS_X = 0
THIGH_POS_Y = 0
CALF_HEADING = 270
CALF_POS_X = -2
CALF_POS_Y = -THIGH_SIZE
FOOT_HEADING = 270
FOOT_POS_X = 5
FOOT_POS_Y = -THIGH_SIZE - CALF_SIZE - 4
UPPERARM_HEADING = 270
UPPERARM_POS_X = -2
UPPERARM_POS_Y = 65
FOREARM_HEADING = 270
FOREARM_POS_X = 0
FOREARM_POS_Y = FOREARM_SIZE - 4
HAND_HEADING = 0
HAND_POS_X = 2
HAND_POS_Y = -4

# CARRY POSITIONS
CARRY_LEFT = 180
CARRY_RIGHT = 0


## INFO

# START POSITIONS
INFO_POS_X = 0
INFO_POS_Y = -380


## SURFACE

# DIMENSIONS
SURFACE_WID = 0.05
SURFACE_LEN = 40

# START POSITIONS
SURFACE_HEADING = 0
SURFACE_POS_X = 0
SURFACE_POS_Y = -100


## BACKGROUND

# DIMENSIONS
BACKGROUND_EMPTY_MID_WID = 19
BACKGROUND_EMPTY_MID_LEN = 40
BACKGROUND_EMPTY_LEFT_WID = 19
BACKGROUND_EMPTY_LEFT_LEN = 40
BACKGROUND_EMPTY_RIGHT_WID = 19
BACKGROUND_EMPTY_RIGHT_LEN = 40
BACKGROUND_LIGHT_WID = 25
BACKGROUND_LIGHT_LEN = 40
BACKGROUND_REGULAR_WID = 25
BACKGROUND_REGULAR_LEN = 40
BACKGROUND_HEAVY_WID = 25
BACKGROUND_HEAVY_LEN = 40
BACKGROUND_CONVEYOR_WID = 25
BACKGROUND_CONVEYOR_LEN = 40

# START POSITIONS
BACKGROUND_EMPTY_MID_HEADING = 0
BACKGROUND_EMPTY_MID_POS_X = 0
BACKGROUND_EMPTY_MID_POS_Y = 210
BACKGROUND_EMPTY_LEFT_HEADING = 0
BACKGROUND_EMPTY_LEFT_POS_X = -3200
BACKGROUND_EMPTY_LEFT_POS_Y = 210
BACKGROUND_EMPTY_RIGHT_HEADING = 0
BACKGROUND_EMPTY_RIGHT_POS_X = 1600
BACKGROUND_EMPTY_RIGHT_POS_Y = 210
BACKGROUND_LIGHT_HEADING = 0
BACKGROUND_LIGHT_POS_X = -1600
BACKGROUND_LIGHT_POS_Y = 150
BACKGROUND_REGULAR_HEADING = 0
BACKGROUND_REGULAR_POS_X = -800
BACKGROUND_REGULAR_POS_Y = 150
BACKGROUND_HEAVY_HEADING = 0
BACKGROUND_HEAVY_POS_X = -2400
BACKGROUND_HEAVY_POS_Y = 150
BACKGROUND_CONVEYOR_HEADING = 0
BACKGROUND_CONVEYOR_POS_X = 800
BACKGROUND_CONVEYOR_POS_Y = 150

# EXTREME POSITIONS
LEFTMOST_TERM = -1600
RIGHTMOST_TERM = 3200


## CONVEYOR BELT

# DIMENSIONS
CONVEYOR_BELT_WID = 2
CONVEYOR_BELT_LEN = 20

# START POSITIONS
CONVEYOR_BELT_HEADING = 0
CONVEYOR_BELT_POS_X = 0
CONVEYOR_BELT_POS_Y = 0


## CONVEYOR DRIVE

# DIMENSIONS
CONVEYOR_DRIVE_WID = 2
CONVEYOR_DRIVE_LEN = 2

# START POSITIONS
CONVEYOR_DRIVE_HEADING = 0
CONVEYOR_DRIVE_POS_X = -200
CONVEYOR_DRIVE_POS_Y = 0


## CONVEYOR TAIL

# DIMENSIONS
CONVEYOR_TAIL_WID = 2
CONVEYOR_TAIL_LEN = 2

# START POSITIONS
CONVEYOR_TAIL_HEADING = 0
CONVEYOR_TAIL_POS_X = 200
CONVEYOR_TAIL_POS_Y = 0


## CONVEYOR LIFT

# DIMENSIONS
CONVEYOR_LIFT_WID = 0.2
CONVEYOR_LIFT_LEN = 8

# START POSITIONS
CONVEYOR_LIFT_HEADING = 0
CONVEYOR_LIFT_POS_X = 305
CONVEYOR_LIFT_POS_Y = 18


## LIGHT LIFT

# DIMENSIONS
LIGHT_LIFT_WID = 0.2
LIGHT_LIFT_LEN = 8

# START POSITIONS
LIGHT_LIFT_HEADING = 0
LIGHT_LIFT_POS_X = 0
LIGHT_LIFT_POS_Y = 18


## REGULAR LIFT

# DIMENSIONS
REGULAR_LIFT_WID = 0.2
REGULAR_LIFT_LEN = 8

# START POSITIONS
REGULAR_LIFT_HEADING = 0
REGULAR_LIFT_POS_X = 0
REGULAR_LIFT_POS_Y = 18


## HEAVY LIFT

# DIMENSIONS
HEAVY_LIFT_WID = 0.2
HEAVY_LIFT_LEN = 8

# START POSITIONS
HEAVY_LIFT_HEADING = 0
HEAVY_LIFT_POS_X = 0
HEAVY_LIFT_POS_Y = 18


## BOX

# DIMENSIONS
BOX_LIGHT_WID = 1
BOX_LIGHT_LEN = 1
BOX_LIGHT_SHAPESIZE = (1, 1, 1)
BOX_REGULAR_WID = 2
BOX_REGULAR_LEN = 2
BOX_REGULAR_SHAPESIZE = (2, 2, 1)
BOX_HEAVY_WID = 3
BOX_HEAVY_LEN = 3
BOX_HEAVY_SHAPESIZE = (3, 3, 1)

# START POSITIONS
BOX_HEADING = 0
BOX_POS_X = 0
BOX_POS_Y = 25

# COLORS
BOX_LIGHT_COLOR = COPPER
BOX_REGULAR_COLOR = MOCHA
BOX_HEAVY_COLOR = MAHOGANY
